### PR TITLE
Fix duplex ADF

### LINKED ISSUE #1087: Regression in support of duplex ADF
Since 1.5.0, specifically commit db44b392420e92c76b9d09fa3d2745915d92086a, an incorrect scan height is sent when using a duplex ADF and no manual height is specified on the command line. Prior to this release, if no height was set, it would send 3507 by default and this would succeed for all scan types (ADF, no ADF, duplex ADF). Since this release, ADF and platen work, but duplex ADF failes with 409 conflict as the height is too large (sends 4200).

This fails because you are sending the MaxHeight from the InputSourceCaps when using the ADF, which is correct for simplex but for duplex you must use AdfDuplexer/AdfDuplexMaxHeight, which is a smaller number (3508). This quick workaround is to set the height CLI flag, but this should be set correctly based on the values from the printer.

I will look into sending a PR shortly.

### PR DESCRIPTION
**Pull request by aaliddell**
Closes #1087 by reading the ADF duplexer capabilities and using that if available

### CODE REVIEW

**Comment by aaliddell** [comment]
This has been tested to work against 9019e in platen, ADF and duplex ADF modes, where previously the duplex ADF failed in 1.6.1

File: src/readDeviceCapabilities.ts [hunk 1]
```diff
@@ -48,5 +48,7 @@ export async function readDeviceCapabilities(): Promise<DeviceCapabilities> {
     platenMaxHeight: scanCaps?.platenMaxHeight || null,
     adfMaxWidth: scanCaps?.adfMaxWidth || null,
     adfMaxHeight: scanCaps?.adfMaxHeight || null,
+    adfDuplexMaxWidth: scanCaps?.adfDuplexMaxWidth || null,
```
Comment (manuc66) [inline src/readDeviceCapabilities.ts:51]: @aaliddell It appears that this small change in the file has increased the complexity of this function beyond CodeFactor's default threshold. Could you look into simplifying this modification? Thank you!

**Comment by aaliddell** [comment]
I have refectored it but the CodeFactor page still links to the previous commit when showing the alert, so might need a restart. Weirdly the complexity factor is supposedly derived from the number of paths through the function and that original one line addition added no new paths, so I don't know why this tripped in the first place when it wasn't before...

**Comment by manuc66** [comment]
Fix released

@aaliddell  thank you very much for this fix !
